version: '3.9'

services:
  backend1:
    container_name: backend1
    build: ./backend1
    command: npm run start:dev
    env_file:
      - ./backend1/.env
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq

  backend2:
    container_name: backend2
    build: ./backend2
    command: npm run start:dev
    env_file:
      - ./backend2/.env
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672